# Generated by Django 5.2.6 on 2025-09-13 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='RM000', max_length=20, unique=True)),
                ('name', models.CharField(default='ห้องเรียนทั่วไป', max_length=100)),
                ('capacity', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('available', 'เปิดให้จอง'), ('unavailable', 'ไม่พร้อมใช้งาน'), ('maintenance', 'ปิดปรับปรุง')], default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.classroom')),
            ],
            options={
                'unique_together': {('date', 'classroom', 'start_time')},
            },
        ),
    ]
