# Generated by Django 5.2.6 on 2025-09-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='available_hours',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
